name: "Okteto Sync"
description: "Synchronise GitHub deployments with Okteto deployments. Removes stale GitHub & Okteto deployments."
inputs:
  dry-run:
    description: "Run the script without making any changes."
    required: false
    default: false
  github-token:
    description: "The GitHub access token."
    required: false
    default: ${{ github.token }}
  okteto-domain:
    description: "The domain where Okteto is hosted. Defaults to Okteto cloud."
    required: false
    default: "cloud.okteto.net"
  ignore-deployments:
    description: "Comma separated list of deployments to ignore."
    required: false
    default: ""
outputs:
  artifact-file:
    description: "The filename for the mender artifact file"
    value: ${{ steps.artifact-filename.outputs.filename }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dry-run }}
    - ${{ inputs.github-token }}
    - ${{ inputs.okteto-domain }}
    - ${{ inputs.ignore-deployments }}
branding:
  color: "green"
  icon: "grid"
